name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Upload Artifact
         uses: actions/upload-artifact@v1
         with:
           name: minigrep
           path: minigrep
    - name: Run tests
      run: cargo test --verbose
